# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Mycv"
license = "MIT"
licenselink = "https://github.com/jsparedes/hugotex/blob/master/LICENSE.md"
description = ""
homepage = "http://jsparedes.github.io/hugotex-docs"
tags = ["xelatex", "latex"]
features = ["multilingual", "markdown"]
min_version = 0.18

[author]
  name = "Jorge Paredes"
  homepage = "https://jsparedes.github.io/"

# If porting an existing theme
[original]
  name = "Byungjin Park"
  homepage = "https://posquit0.com/"
  repo = "https://github.com/posquit0/Awesome-CV"
